import { useState } from 'react';
import { Key, Code, BarChart3, Activity, Zap, Plus, Trash2, Download, FileText, Users, Building2, AlertTriangle, CheckCircle2, Clock, DollarSign, TrendingUp, Globe } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card } from '@/components/ui/Card';
import { Spinner } from '@/components/ui/Spinner';
import { Badge } from '@/components/ui/Badge';
import { cn, timeAgo } from '@/lib/utils';
import { useAPIPlatformDashboard, useCreateAPIKey, useRevokeAPIKey, useCreateOAuthClient, useCreateDeveloperOrg, useGenerateOpenAPISpec, useGenerateSDK } from '@/hooks/useAPIPlatform';

const TABS = [
  { id: 'overview', label: 'Overview', icon: BarChart3 },
  { id: 'keys', label: 'API Keys', icon: Key },
  { id: 'oauth', label: 'OAuth Clients', icon: Globe },
  { id: 'logs', label: 'API Logs', icon: Activity },
  { id: 'usage', label: 'Usage', icon: TrendingUp },
  { id: 'devs', label: 'Developers', icon: Users },
  { id: 'docs', label: 'Documentation', icon: FileText },
  { id: 'sdks', label: 'SDKs', icon: Code },
] as const;

type TabId = (typeof TABS)[number]['id'];

export function APIPlatformPage() {
  const { data: dash, isLoading } = useAPIPlatformDashboard();
  const createKey = useCreateAPIKey();
  const revokeKey = useRevokeAPIKey();
  const createClient = useCreateOAuthClient();
  const createOrg = useCreateDeveloperOrg();
  const genOpenAPI = useGenerateOpenAPISpec();
  const genSDK = useGenerateSDK();
  const [tab, setTab] = useState<TabId>('overview');

  if (isLoading) {
    return (<div><PageHeader title="API Platform" description="Public REST API with keys, OAuth, rate limits, usage tracking, and developer portal." /><div className="flex justify-center py-20"><Spinner className="h-8 w-8" /></div></div>);
  }

  if (!dash || dash.apiKeys.length === 0) {
    return (<div><PageHeader title="API Platform" description="Public REST API with keys, OAuth, rate limits, usage tracking, and developer portal." /><Card className="p-6"><div className="flex flex-col items-center justify-center py-16 space-y-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-r from-gold-400 to-gold-300/10 border border-brand-500/20"><Key className="h-8 w-8 text-brand-400" /></div><div className="text-center space-y-2"><h3 className="text-lg font-semibold text-ink-500">Public API Platform</h3><p className="text-sm text-ink-500 max-w-md mx-auto leading-relaxed">Expose every module through a versioned REST API with API keys, OAuth2 clients, rate limits, usage tracking, and auto-generated documentation. Create your first API key to begin.</p></div><button onClick={() => createKey.mutate({ name: 'Default API Key' })} disabled={createKey.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300 px-6 py-2.5 text-sm font-medium text-maroon-950 hover:bg-brand-300/15 disabled:opacity-50"><Zap className="h-4 w-4" />{createKey.isPending ? 'Creating...' : 'Create API Key'}</button></div></Card></div>);
  }

  return (
    <div>
      <PageHeader title="API Platform" description="Public REST API with keys, OAuth, rate limits, usage tracking, and developer portal." actions={<div className="flex items-center gap-2"><button onClick={() => genOpenAPI.mutate()} disabled={genOpenAPI.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-3 py-2 text-sm font-medium text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20 disabled:opacity-50"><FileText className="h-3.5 w-3.5" />Generate OpenAPI</button><button onClick={() => createKey.mutate({ name: `API Key ${dash.apiKeys.length + 1}` })} disabled={createKey.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300 px-4 py-2 text-sm font-medium text-maroon-950 hover:bg-brand-300/15 disabled:opacity-50"><Plus className="h-3.5 w-3.5" />New Key</button></div>} />
      <div className="flex items-start gap-3 mb-6 rounded-xl bg-gradient-to-r from-gold-400 to-gold-300/5 border border-brand-500/10 p-4"><Activity className="h-5 w-5 text-brand-400 shrink-0 mt-0.5" /><div className="flex-1"><p className="text-sm text-ink-500">{dash.totalRequests.toLocaleString()} total API requests across {dash.activeKeys} active keys and {dash.activeApps} developer apps. Error rate: {dash.errorRate.toFixed(2)}%. Avg latency: {dash.avgLatency.toFixed(0)}ms.</p><p className="text-xs text-ink-500 mt-0.5">Today: {dash.requestsToday.toLocaleString()} requests · This month: {dash.requestsThisMonth.toLocaleString()} requests · Total cost: ${dash.totalCost.toFixed(2)}</p></div></div>
      <Card>
        <div className="border-b border-gold-500/12 px-2"><div className="flex items-center gap-1 overflow-x-auto scrollbar-thin">{TABS.map((t) => (<button key={t.id} onClick={() => setTab(t.id)} className={cn('flex items-center gap-1.5 px-3 py-2.5 text-xs font-medium border-b-2 transition-colors whitespace-nowrap', tab === t.id ? 'border-brand-500 text-brand-400' : 'border-transparent text-ink-500 hover:text-ink-500')}><t.icon className="h-3.5 w-3.5" />{t.label}</button>))}</div></div>
        <div className="p-4">
          {tab === 'overview' && (<div className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[<Card key="r" className="p-4"><div className="flex items-center gap-2 mb-1"><Activity className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Total Requests</span></div><p className="text-2xl font-bold text-ink-500">{dash.totalRequests.toLocaleString()}</p></Card>, <Card key="e" className="p-4"><div className="flex items-center gap-2 mb-1"><AlertTriangle className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Errors</span></div><p className="text-2xl font-bold text-ink-500">{dash.totalErrors}</p></Card>, <Card key="k" className="p-4"><div className="flex items-center gap-2 mb-1"><Key className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Active Keys</span></div><p className="text-2xl font-bold text-ink-500">{dash.activeKeys}</p></Card>, <Card key="a" className="p-4"><div className="flex items-center gap-2 mb-1"><Users className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Developer Apps</span></div><p className="text-2xl font-bold text-ink-500">{dash.activeApps}</p></Card>]}</div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[<Card key="t" className="p-4"><div className="flex items-center gap-2 mb-1"><Clock className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Avg Latency</span></div><p className="text-2xl font-bold text-ink-500">{dash.avgLatency.toFixed(0)}ms</p></Card>, <Card key="c" className="p-4"><div className="flex items-center gap-2 mb-1"><DollarSign className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Total Cost</span></div><p className="text-2xl font-bold text-ink-500">${dash.totalCost.toFixed(2)}</p></Card>, <Card key="o" className="p-4"><div className="flex items-center gap-2 mb-1"><Building2 className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Dev Orgs</span></div><p className="text-2xl font-bold text-ink-500">{dash.activeOrgs}</p></Card>, <Card key="er" className="p-4"><div className="flex items-center gap-2 mb-1"><TrendingUp className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Error Rate</span></div><p className="text-2xl font-bold text-ink-500">{dash.errorRate.toFixed(2)}%</p></Card>]}</div></div>)}
          {tab === 'keys' && (<div className="space-y-2">{dash.apiKeys.map((k) => { const key = k as Record<string, unknown>; return (<Card key={key.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Key className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{key.key_name as string}</p><p className="text-xs text-ink-500 font-mono">{key.key_prefix as string}... · {timeAgo(key.created_at as string)}</p></div></div><div className="flex items-center gap-2"><Badge tone={key.is_active ? 'success' : 'neutral'} dot>{key.is_active ? 'Active' : 'Revoked'}</Badge>{key.is_active && <button onClick={() => revokeKey.mutate(key.id as string)} className="rounded-lg bg-error-500/10 px-2.5 py-1 text-xs text-error-400 hover:bg-error-500/20"><Trash2 className="h-3 w-3" /></button>}</div></div><div className="mt-2 flex flex-wrap gap-1">{(key.scopes as string[]).map((s) => <Badge key={s} tone="brand">{s}</Badge>)}</div></Card>); })}</div>)}
          {tab === 'oauth' && (<div className="space-y-2">{dash.oauthClients.length === 0 ? <div className="text-center py-8 text-sm text-ink-500">No OAuth clients. <button onClick={() => createClient.mutate({ name: 'Default Client', redirectUris: [] })} className="text-brand-400 hover:underline">Create one</button></div> : dash.oauthClients.map((c) => { const client = c as Record<string, unknown>; return (<Card key={client.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Globe className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{client.client_name as string}</p><p className="text-xs text-ink-500 font-mono">{client.client_id as string}</p></div></div><Badge tone={client.is_active ? 'success' : 'neutral'} dot>{client.is_active ? 'Active' : 'Inactive'}</Badge></div></Card>); })}</div>)}
          {tab === 'logs' && (<div className="space-y-2">{dash.logs.slice(0, 20).map((l) => { const log = l as Record<string, unknown>; return (<Card key={log.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Code className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500 font-mono">{log.method as string} {log.endpoint as string}</p><p className="text-xs text-ink-500">{timeAgo(log.created_at as string)} · {log.latency_ms as number ?? 0}ms</p></div></div><Badge tone={log.status_code as number < 300 ? 'success' : log.status_code as number < 500 ? 'warning' : 'error'}>{log.status_code as number}</Badge></div></Card>); })}</div>)}
          {tab === 'usage' && (<div className="space-y-2">{dash.usage.slice(0, 20).map((u) => { const usage = u as Record<string, unknown>; return (<Card key={usage.id as string} className="p-3"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-ink-500">{usage.usage_date as string}</p><p className="text-xs text-ink-500">{(usage.request_count as number).toLocaleString()} requests · ${(usage.total_cost as number).toFixed(2)} cost</p></div><Badge tone="brand">{(usage.total_tokens as number).toLocaleString()} tokens</Badge></div></Card>); })}</div>)}
          {tab === 'devs' && (<div className="space-y-2">{dash.developerOrgs.length === 0 ? <div className="text-center py-8 text-sm text-ink-500">No developer organizations. <button onClick={() => createOrg.mutate({ name: 'Default Org' })} className="text-brand-400 hover:underline">Create one</button></div> : dash.developerOrgs.map((o) => { const org = o as Record<string, unknown>; return (<Card key={org.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Building2 className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{org.org_name as string}</p><p className="text-xs text-ink-500">{org.org_slug as string} · {org.plan_tier as string} plan · {org.total_apps as number} apps</p></div></div><Badge tone={org.org_status as string === 'active' ? 'success' : 'neutral'} dot>{org.org_status as string}</Badge></div></Card>); })}</div>)}
          {tab === 'docs' && (<div className="space-y-2">{dash.documentation.length === 0 ? <div className="text-center py-8 text-sm text-ink-500">No documentation generated. <button onClick={() => genOpenAPI.mutate()} className="text-brand-400 hover:underline">Generate OpenAPI spec</button></div> : dash.documentation.map((d) => { const doc = d as Record<string, unknown>; return (<Card key={doc.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">OpenAPI {doc.doc_version as string}</p><p className="text-xs text-ink-500">{timeAgo(doc.created_at as string)}</p></div></div><Badge tone={doc.is_published ? 'success' : 'neutral'}>{doc.is_published ? 'Published' : 'Draft'}</Badge></div></Card>); })}</div>)}
          {tab === 'sdks' && (<div className="space-y-2">{dash.sdkVersions.length === 0 ? <div className="text-center py-8 space-y-2"><p className="text-sm text-ink-500">No SDKs generated.</p><div className="flex flex-wrap justify-center gap-2">{['javascript', 'typescript', 'python', 'go', 'java', 'php', 'csharp', 'node'].map((lang) => <button key={lang} onClick={() => genSDK.mutate(lang)} disabled={genSDK.isPending} className="rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-3 py-1.5 text-xs text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20 disabled:opacity-50">{lang}</button>)}</div></div> : dash.sdkVersions.map((s) => { const sdk = s as Record<string, unknown>; return (<Card key={sdk.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Code className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{sdk.language as string} SDK v{sdk.version as string}</p><p className="text-xs text-ink-500">{sdk.package_name as string ?? 'N/A'} · {sdk.package_registry as string ?? 'N/A'}</p></div></div><div className="flex items-center gap-2"><Badge tone={sdk.is_stable ? 'success' : 'neutral'}>{sdk.is_stable ? 'Stable' : 'Preview'}</Badge>{sdk.download_url && <a href={sdk.download_url as string} className="rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-2.5 py-1 text-xs text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20"><Download className="h-3 w-3" /></a>}</div></div></Card>); })}</div>)}
        </div>
      </Card>
    </div>
  );
}
