import { useState } from 'react';
import { Building2, Users, Shield, ShieldCheck, Lock, FileText, Globe, Plus, Zap, Activity, AlertTriangle, CheckCircle2, Layers, MapPin, Briefcase, Clock, Server, Key } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card } from '@/components/ui/Card';
import { Spinner } from '@/components/ui/Spinner';
import { Badge } from '@/components/ui/Badge';
import { cn, timeAgo } from '@/lib/utils';
import { useEnterpriseAdminDashboard, useCreateEnterpriseOrg, useCreateDepartment, useCreateTeam, useConfigureSSO, useCreateSecurityPolicy, useUpdateCompliance } from '@/hooks/useEnterpriseAdmin';

const TABS = [
  { id: 'overview', label: 'Overview', icon: Building2 },
  { id: 'orgs', label: 'Organizations', icon: Building2 },
  { id: 'departments', label: 'Departments', icon: Layers },
  { id: 'teams', label: 'Teams', icon: Users },
  { id: 'regions', label: 'Regions', icon: MapPin },
  { id: 'business-units', label: 'Business Units', icon: Briefcase },
  { id: 'sso', label: 'SSO / SAML', icon: Key },
  { id: 'security', label: 'Security Policies', icon: Shield },
  { id: 'compliance', label: 'Compliance', icon: ShieldCheck },
  { id: 'audit', label: 'Audit Logs', icon: FileText },
] as const;

type TabId = (typeof TABS)[number]['id'];

export function EnterpriseAdminPage() {
  const { data: dash, isLoading } = useEnterpriseAdminDashboard();
  const createOrg = useCreateEnterpriseOrg();
  const createDept = useCreateDepartment();
  const createTeam = useCreateTeam();
  const configureSSO = useConfigureSSO();
  const createPolicy = useCreateSecurityPolicy();
  const updateCompliance = useUpdateCompliance();
  const [tab, setTab] = useState<TabId>('overview');

  if (isLoading) return (<div><PageHeader title="Enterprise Administration" description="Organizations, departments, SSO, security policies, compliance, and audit logs." /><div className="flex justify-center py-20"><Spinner className="h-8 w-8" /></div></div>);

  if (!dash || dash.totalOrganizations === 0) {
    return (<div><PageHeader title="Enterprise Administration" description="Organizations, departments, SSO, security policies, compliance, and audit logs." /><Card className="p-6"><div className="flex flex-col items-center justify-center py-16 space-y-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-r from-gold-400 to-gold-300/10 border border-brand-500/20"><Building2 className="h-8 w-8 text-brand-400" /></div><div className="text-center space-y-2"><h3 className="text-lg font-semibold text-ink-500">Enterprise Administration Console</h3><p className="text-sm text-ink-500 max-w-md mx-auto leading-relaxed">Manage enterprise organizations, departments, regions, business units, teams, SSO/SAML, SCIM, security policies, compliance (SOC2, ISO, GDPR), and audit logs.</p></div><button onClick={() => createOrg.mutate({ name: 'Enterprise Organization' })} disabled={createOrg.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300 px-6 py-2.5 text-sm font-medium text-maroon-950 hover:bg-brand-300/15 disabled:opacity-50"><Zap className="h-4 w-4" />{createOrg.isPending ? 'Creating...' : 'Create Enterprise Org'}</button></div></Card></div>);
  }

  return (
    <div>
      <PageHeader title="Enterprise Administration" description="Organizations, departments, SSO, security policies, compliance, and audit logs." actions={<div className="flex items-center gap-2"><button onClick={() => createOrg.mutate({ name: `Org ${dash.totalOrganizations + 1}` })} disabled={createOrg.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300 px-4 py-2 text-sm font-medium text-maroon-950 hover:bg-brand-300/15 disabled:opacity-50"><Plus className="h-3.5 w-3.5" />New Org</button></div>} />
      <div className="flex items-start gap-3 mb-6 rounded-xl bg-gradient-to-r from-gold-400 to-gold-300/5 border border-brand-500/10 p-4"><Building2 className="h-5 w-5 text-brand-400 shrink-0 mt-0.5" /><div className="flex-1"><p className="text-sm text-ink-500">{dash.totalOrganizations} enterprise organizations with {dash.totalDepartments} departments, {dash.totalTeams} teams, and {dash.totalRegions} regions. {dash.activeSSOConfigs} SSO configs active, {dash.enforcedPolicies} security policies enforced.</p><p className="text-xs text-ink-500 mt-0.5">Compliance score: {dash.complianceScore.toFixed(0)}/100 · {dash.totalAuditEvents} audit events logged</p></div></div>
      <Card>
        <div className="border-b border-gold-500/12 px-2"><div className="flex items-center gap-1 overflow-x-auto scrollbar-thin">{TABS.map((t) => (<button key={t.id} onClick={() => setTab(t.id)} className={cn('flex items-center gap-1.5 px-3 py-2.5 text-xs font-medium border-b-2 transition-colors whitespace-nowrap', tab === t.id ? 'border-brand-500 text-brand-400' : 'border-transparent text-ink-500 hover:text-ink-500')}><t.icon className="h-3.5 w-3.5" />{t.label}</button>))}</div></div>
        <div className="p-4">
          {tab === 'overview' && (<div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[<Card key="o" className="p-4"><div className="flex items-center gap-2 mb-1"><Building2 className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Organizations</span></div><p className="text-2xl font-bold text-ink-500">{dash.totalOrganizations}</p></Card>, <Card key="d" className="p-4"><div className="flex items-center gap-2 mb-1"><Layers className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Departments</span></div><p className="text-2xl font-bold text-ink-500">{dash.totalDepartments}</p></Card>, <Card key="t" className="p-4"><div className="flex items-center gap-2 mb-1"><Users className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Teams</span></div><p className="text-2xl font-bold text-ink-500">{dash.totalTeams}</p></Card>, <Card key="r" className="p-4"><div className="flex items-center gap-2 mb-1"><MapPin className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Regions</span></div><p className="text-2xl font-bold text-ink-500">{dash.totalRegions}</p></Card>]}</div>)}
          {tab === 'orgs' && (<div className="space-y-2">{dash.organizations.map((o) => { const org = o as Record<string, unknown>; return (<Card key={org.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Building2 className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{org.org_name as string}</p><p className="text-xs text-ink-500">{org.org_slug as string} · {org.contract_type as string ?? 'N/A'} · {org.seat_count as number} seats</p></div></div><Badge tone={org.status as string === 'active' ? 'success' : 'neutral'} dot>{org.status as string}</Badge></div></Card>); })}</div>)}
          {tab === 'departments' && (<div className="space-y-2">{dash.departments.length === 0 ? <div className="text-center py-8 text-sm text-ink-500">No departments. <button onClick={() => createDept.mutate({ name: 'Sales' })} className="text-brand-400 hover:underline">Create one</button></div> : dash.departments.map((d) => { const dept = d as Record<string, unknown>; return (<Card key={dept.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Layers className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{dept.department_name as string}</p><p className="text-xs text-ink-500">{dept.budget_allocation ? `$${(dept.budget_allocation as number).toLocaleString()}` : 'No budget'}</p></div></div><Badge tone={dept.is_active ? 'success' : 'neutral'} dot>{dept.is_active ? 'Active' : 'Inactive'}</Badge></div></Card>); })}</div>)}
          {tab === 'teams' && (<div className="space-y-2">{dash.teams.length === 0 ? <div className="text-center py-8 text-sm text-ink-500">No teams. <button onClick={() => createTeam.mutate({ name: 'Team Alpha' })} className="text-brand-400 hover:underline">Create one</button></div> : dash.teams.map((t) => { const team = t as Record<string, unknown>; return (<Card key={team.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Users className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{team.team_name as string}</p><p className="text-xs text-ink-500">{team.team_description as string ?? 'No description'}</p></div></div><Badge tone={team.is_active ? 'success' : 'neutral'} dot>{team.is_active ? 'Active' : 'Inactive'}</Badge></div></Card>); })}</div>)}
          {tab === 'regions' && (<div className="space-y-2">{dash.regions.length === 0 ? <div className="text-center py-8 text-sm text-ink-500">No regions configured.</div> : dash.regions.map((r) => { const reg = r as Record<string, unknown>; return (<Card key={reg.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><MapPin className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{reg.region_name as string}</p><p className="text-xs text-ink-500">{(reg.countries as string[]).join(', ')}</p></div></div><Badge tone={reg.is_active ? 'success' : 'neutral'} dot>{reg.is_active ? 'Active' : 'Inactive'}</Badge></div></Card>); })}</div>)}
          {tab === 'business-units' && (<div className="space-y-2">{dash.businessUnits.length === 0 ? <div className="text-center py-8 text-sm text-ink-500">No business units.</div> : dash.businessUnits.map((b) => { const bu = b as Record<string, unknown>; return (<Card key={bu.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Briefcase className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{bu.bu_name as string}</p><p className="text-xs text-ink-500">{bu.bu_code as string ?? 'N/A'}</p></div></div><Badge tone={bu.is_active ? 'success' : 'neutral'} dot>{bu.is_active ? 'Active' : 'Inactive'}</Badge></div></Card>); })}</div>)}
          {tab === 'sso' && (<div className="space-y-2">{dash.ssoConfigs.length === 0 ? <div className="text-center py-8 space-y-2"><p className="text-sm text-ink-500">No SSO configurations.</p><button onClick={() => configureSSO.mutate({ ssoType: 'saml' })} disabled={configureSSO.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-3 py-2 text-sm text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20"><Key className="h-3.5 w-3.5" />Configure SSO</button></div> : dash.ssoConfigs.map((s) => { const sso = s as Record<string, unknown>; return (<Card key={sso.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Key className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{sso.sso_type as string} Configuration</p><p className="text-xs text-ink-500">{sso.sso_entity_id as string ?? 'No entity ID'}</p></div></div><Badge tone={sso.is_active ? 'success' : 'neutral'} dot>{sso.is_active ? 'Active' : 'Inactive'}</Badge></div></Card>); })}</div>)}
          {tab === 'security' && (<div className="space-y-2">{dash.securityPolicies.length === 0 ? <div className="text-center py-8 space-y-2"><p className="text-sm text-ink-500">No security policies.</p><button onClick={() => createPolicy.mutate({ policyType: 'ip_restriction', policyName: 'IP Restrictions' })} disabled={createPolicy.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-3 py-2 text-sm text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20"><Shield className="h-3.5 w-3.5" />Create Policy</button></div> : dash.securityPolicies.map((p) => { const pol = p as Record<string, unknown>; return (<Card key={pol.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{pol.policy_name as string}</p><p className="text-xs text-ink-500">{pol.policy_type as string}</p></div></div><Badge tone={pol.is_enforced ? 'success' : 'neutral'} dot>{pol.is_enforced ? 'Enforced' : 'Not Enforced'}</Badge></div></Card>); })}</div>)}
          {tab === 'compliance' && (<div className="space-y-2">{dash.compliance.length === 0 ? <div className="text-center py-8 space-y-2"><p className="text-sm text-ink-500">No compliance tracking.</p><div className="flex flex-wrap justify-center gap-2">{['SOC2', 'ISO27001', 'GDPR'].map((c) => <button key={c} onClick={() => updateCompliance.mutate({ complianceType: c, status: 'in_progress' })} disabled={updateCompliance.isPending} className="rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-3 py-1.5 text-xs text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20 disabled:opacity-50">{c}</button>)}</div></div> : dash.compliance.map((c) => { const comp = c as Record<string, unknown>; return (<Card key={comp.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{comp.compliance_type as string}</p><p className="text-xs text-ink-500">Score: {comp.compliance_score as number ?? 0}/100 · {comp.data_residency_region as string ?? 'No region'}</p></div></div><Badge tone={comp.compliance_status as string === 'compliant' ? 'success' : comp.compliance_status as string === 'in_progress' ? 'warning' : 'neutral'} dot>{comp.compliance_status as string}</Badge></div></Card>); })}</div>)}
          {tab === 'audit' && (<div className="space-y-2">{dash.auditLogs.slice(0, 30).map((a) => { const audit = a as Record<string, unknown>; return (<Card key={audit.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{audit.action as string}</p><p className="text-xs text-ink-500">{audit.resource_type as string ?? 'N/A'} · {timeAgo(audit.created_at as string)}</p></div></div><Badge tone={audit.severity as string === 'critical' ? 'error' : audit.severity as string === 'warning' ? 'warning' : 'neutral'}>{audit.severity as string}</Badge></div></Card>); })}</div>)}
        </div>
      </Card>
    </div>
  );
}
