import { useState } from 'react';
import { Cpu, Zap, Activity, CheckCircle2, ShieldAlert, Layers, RefreshCw, Lightbulb, Brain, AlertTriangle, Award, Clock, FileText, TrendingUp, Users, Heart, Sparkles } from 'lucide-react';
import { PageHeader } from '@/components/ui/PageHeader';
import { Card } from '@/components/ui/Card';
import { Spinner } from '@/components/ui/Spinner';
import { Badge } from '@/components/ui/Badge';
import { cn, timeAgo } from '@/lib/utils';
import { useWorkforceDashboard, useInitializeAgents, useExecuteTask, useApproveTask, useRejectTask, useRetryTask, useCancelTask, useGenerateWorkPlan, usePrioritizeQueue } from '@/hooks/useAutonomousWorkforce';
import { useAuth } from '@/hooks/useAuth';

const TABS = [
  { id: 'dashboard', label: 'Dashboard', icon: Cpu },
  { id: 'agents', label: 'Agents', icon: Users },
  { id: 'queue', label: 'Task Queue', icon: Clock },
  { id: 'running', label: 'Running Tasks', icon: Activity },
  { id: 'completed', label: 'Completed Tasks', icon: CheckCircle2 },
  { id: 'approvals', label: 'Approvals', icon: ShieldAlert },
  { id: 'workflows', label: 'Workflows', icon: Layers },
  { id: 'collaboration', label: 'Collaboration', icon: RefreshCw },
  { id: 'performance', label: 'Performance', icon: TrendingUp },
  { id: 'learning', label: 'Learning', icon: Lightbulb },
  { id: 'memory', label: 'Memory', icon: Brain },
  { id: 'reasoning', label: 'Reasoning', icon: Brain },
  { id: 'results', label: 'Executions', icon: CheckCircle2 },
  { id: 'errors', label: 'Failures', icon: AlertTriangle },
  { id: 'metrics', label: 'Metrics', icon: Activity },
  { id: 'schedules', label: 'Schedules', icon: Clock },
  { id: 'logs', label: 'Logs', icon: FileText },
  { id: 'decisions', label: 'Decisions', icon: Award },
] as const;

type TabId = (typeof TABS)[number]['id'];

export function WorkforcePage() {
  const { data: wd, isLoading } = useWorkforceDashboard();
  const initAgents = useInitializeAgents();
  const executeTask = useExecuteTask();
  const approveTask = useApproveTask();
  const rejectTask = useRejectTask();
  const retryTask = useRetryTask();
  const cancelTask = useCancelTask();
  const generateWorkPlan = useGenerateWorkPlan();
  const prioritizeQueue = usePrioritizeQueue();
  const { user } = useAuth();
  const [tab, setTab] = useState<TabId>('dashboard');

  const handleApprove = (taskId: string) => { if (user) approveTask.mutate({ taskId, userId: user.id }); };
  const handleReject = (taskId: string) => { if (user) rejectTask.mutate({ taskId, userId: user.id, reason: 'Rejected by user' }); };

  if (isLoading) {
    return (<div><PageHeader title="Autonomous AI Workforce" description="AI employees controlled by the AI CEO — executing tasks automatically while humans approve high-risk decisions." /><div className="flex justify-center py-20"><Spinner className="h-8 w-8" /></div></div>);
  }

  if (!wd || wd.profiles.length === 0) {
    return (<div><PageHeader title="Autonomous AI Workforce" description="AI employees controlled by the AI CEO — executing tasks automatically while humans approve high-risk decisions." /><Card className="p-6"><div className="flex flex-col items-center justify-center py-16 space-y-4"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-r from-gold-400 to-gold-300/10 border border-brand-500/20"><Cpu className="h-8 w-8 text-brand-400" /></div><div className="text-center space-y-2"><h3 className="text-lg font-semibold text-ink-500">Autonomous AI Workforce</h3><p className="text-sm text-ink-500 max-w-md mx-auto leading-relaxed">I manage a team of 9 specialized AI employees. Each agent has memory, objectives, skills, tools, permissions, and execution history. Initialize the workforce to begin.</p></div><button onClick={() => initAgents.mutate()} disabled={initAgents.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300 px-6 py-2.5 text-sm font-medium text-maroon-950 hover:bg-brand-300/15 disabled:opacity-50"><Zap className="h-4 w-4" />{initAgents.isPending ? 'Initializing...' : 'Initialize Workforce'}</button></div></Card></div>);
  }

  const statusTone: Record<string, string> = { idle: 'neutral', busy: 'brand', waiting: 'warning', paused: 'neutral', error: 'error', offline: 'neutral', initializing: 'brand' };
  const taskStatusTone: Record<string, string> = { pending: 'neutral', assigned: 'brand', running: 'brand', waiting: 'warning', blocked: 'warning', completed: 'success', failed: 'error', cancelled: 'neutral', retrying: 'warning', escalated: 'error' };
  const priorityTone: Record<string, string> = { critical: 'error', high: 'warning', medium: 'brand', low: 'neutral' };

  const GenericList = ({ items, icon: Icon, titleKey, descKey }: { items: Array<Record<string, unknown>>; icon: typeof Brain; titleKey: string; descKey: string }) => {
    if (items.length === 0) return <div className="text-center py-8 text-sm text-ink-500">No data available.</div>;
    return (<div className="space-y-2">{items.slice(0, 20).map((item, i) => (<Card key={i} className="p-3 flex items-start gap-2"><Icon className="h-4 w-4 text-brand-400 shrink-0 mt-0.5" /><div className="flex-1"><p className="text-sm text-ink-500">{(item[titleKey] as string) ?? 'Item'}</p><p className="text-xs text-ink-500 mt-0.5">{((item[descKey] as string) ?? '').slice(0, 120)}</p></div></Card>))}</div>);
  };

  return (
    <div>
      <PageHeader title="Autonomous AI Workforce" description="AI employees controlled by the AI CEO — executing tasks automatically while humans approve high-risk decisions." actions={<div className="flex items-center gap-2"><button onClick={() => generateWorkPlan.mutate()} disabled={generateWorkPlan.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-3 py-2 text-sm font-medium text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20 disabled:opacity-50"><Zap className="h-3.5 w-3.5" />Generate Work Plan</button><button onClick={() => prioritizeQueue.mutate()} disabled={prioritizeQueue.isPending} className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-3 py-2 text-sm font-medium text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20 disabled:opacity-50"><RefreshCw className="h-3.5 w-3.5" />Prioritize</button></div>} />
      <Card>
        <div className="border-b border-gold-500/12 px-2"><div className="flex items-center gap-1 overflow-x-auto scrollbar-thin">{TABS.map((t) => (<button key={t.id} onClick={() => setTab(t.id)} className={cn('flex items-center gap-1.5 px-3 py-2.5 text-xs font-medium border-b-2 transition-colors whitespace-nowrap', tab === t.id ? 'border-brand-500 text-brand-400' : 'border-transparent text-ink-500 hover:text-ink-500')}><t.icon className="h-3.5 w-3.5" />{t.label}</button>))}</div></div>
        <div className="p-4">
          {tab === 'dashboard' && (<div className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[<Card key="a" className="p-4"><div className="flex items-center gap-2 mb-1"><Users className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Total Agents</span></div><p className="text-2xl font-bold text-ink-500">{wd.totalAgents}</p><p className="text-xs text-ink-500">{wd.activeAgents} active</p></Card>, <Card key="r" className="p-4"><div className="flex items-center gap-2 mb-1"><Activity className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Running Tasks</span></div><p className="text-2xl font-bold text-ink-500">{wd.runningTasks}</p><p className="text-xs text-ink-500">{wd.pendingTasks} pending</p></Card>, <Card key="c" className="p-4"><div className="flex items-center gap-2 mb-1"><CheckCircle2 className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Completed</span></div><p className="text-2xl font-bold text-ink-500">{wd.completedTasks}</p><p className="text-xs text-ink-500">{wd.failedTasks} failed</p></Card>, <Card key="p" className="p-4"><div className="flex items-center gap-2 mb-1"><ShieldAlert className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Pending Approvals</span></div><p className="text-2xl font-bold text-ink-500">{wd.pendingApprovals}</p></Card>]}</div><div className="grid grid-cols-2 md:grid-cols-3 gap-4">{[<Card key="conf" className="p-4"><div className="flex items-center gap-2 mb-1"><Sparkles className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Avg Confidence</span></div><p className="text-2xl font-bold text-ink-500">{wd.avgConfidence.toFixed(0)}%</p></Card>, <Card key="health" className="p-4"><div className="flex items-center gap-2 mb-1"><Heart className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Avg Health</span></div><p className="text-2xl font-bold text-ink-500">{wd.avgHealthScore.toFixed(0)}</p></Card>, <Card key="wl" className="p-4"><div className="flex items-center gap-2 mb-1"><Cpu className="h-4 w-4 text-brand-400" /><span className="text-xs text-ink-500">Total Workload</span></div><p className="text-2xl font-bold text-ink-500">{wd.totalWorkload.toFixed(0)}%</p></Card>]}</div></div>)}
          {tab === 'agents' && (<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{wd.profiles.map((p) => { const profile = p as Record<string, unknown>; const status = wd.statuses.find((s) => (s as Record<string, unknown>).agent_id === profile.id) as Record<string, unknown> | undefined; const health = wd.health.find((h) => (h as Record<string, unknown>).agent_id === profile.id) as Record<string, unknown> | undefined; return (<Card key={profile.id as string} className="p-4 space-y-3"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-r from-gold-400 to-gold-300/10 text-lg">{profile.avatar_emoji as string}</div><div><p className="text-sm font-semibold text-ink-500">{profile.agent_name as string}</p><p className="text-xs text-ink-500 capitalize">{profile.agent_type as string}</p></div></div><Badge tone={(statusTone[status?.status as string] ?? 'neutral') as never} dot>{status?.status as string ?? 'idle'}</Badge></div><p className="text-xs text-ink-500 leading-relaxed line-clamp-2">{profile.agent_description as string}</p><div className="flex items-center gap-3 text-xs"><span className="flex items-center gap-1"><Heart className="h-3 w-3 text-success-400" /><span className="text-ink-500">{(health?.health_score as number ?? 100).toFixed(0)}</span></span><span className="flex items-center gap-1"><Activity className="h-3 w-3 text-ink-500" /><span className="text-ink-500">{(status?.workload_percent as number ?? 0).toFixed(0)}% load</span></span><span className="flex items-center gap-1"><CheckCircle2 className="h-3 w-3 text-success-400" /><span className="text-ink-500">{status?.tasks_completed_today as number ?? 0} done</span></span></div></Card>); })}</div>)}
          {tab === 'queue' && (<div className="space-y-2">{wd.tasks.filter((t) => ['pending','assigned'].includes((t as Record<string, unknown>).status as string)).map((t) => { const task = t as Record<string, unknown>; return (<Card key={task.id as string} className="p-3 space-y-2"><div className="flex items-start justify-between"><div className="flex-1"><p className="text-sm font-medium text-ink-500">{task.task_title as string}</p>{task.task_description && <p className="text-xs text-ink-500 mt-0.5 line-clamp-2">{task.task_description as string}</p>}</div><Badge tone={(taskStatusTone[task.status as string] ?? 'neutral') as never} dot>{task.status as string}</Badge></div><div className="flex items-center gap-2 text-xs"><Badge tone={(priorityTone[task.priority as string] ?? 'neutral') as never}>{task.priority as string}</Badge><Badge tone="brand"><Sparkles className="h-3 w-3 mr-1" />{(task.confidence as number).toFixed(0)}%</Badge>{task.approval_required && <Badge tone="warning">Needs {task.approval_level as string}</Badge>}<span className="text-ink-500">{timeAgo(task.created_at as string)}</span></div><div className="flex items-center gap-2">{task.status === 'pending' && task.approval_required && <button onClick={() => handleApprove(task.id as string)} className="rounded-lg bg-success-500/10 px-2.5 py-1 text-xs text-success-400 hover:bg-success-500/20">Approve</button>}{task.status === 'pending' && task.approval_required && <button onClick={() => handleReject(task.id as string)} className="rounded-lg bg-error-500/10 px-2.5 py-1 text-xs text-error-400 hover:bg-error-500/20">Reject</button>}{task.status === 'assigned' && <button onClick={() => executeTask.mutate(task.id as string)} className="rounded-lg bg-gradient-to-r from-gold-400 to-gold-300/10 px-2.5 py-1 text-xs text-brand-400 hover:bg-gradient-to-r from-gold-400 to-gold-300/20">Execute</button>}{task.status === 'failed' && <button onClick={() => retryTask.mutate(task.id as string)} className="rounded-lg bg-warning-500/10 px-2.5 py-1 text-xs text-warning-400 hover:bg-warning-500/20">Retry</button>}{['pending','assigned','waiting'].includes(task.status as string) && <button onClick={() => cancelTask.mutate(task.id as string)} className="rounded-lg bg-gray-500/10 px-2.5 py-1 text-xs text-ink-500 hover:bg-gray-500/20">Cancel</button>}</div></Card>); })}</div>)}
          {tab === 'running' && (<div className="space-y-2">{wd.tasks.filter((t) => (t as Record<string, unknown>).status === 'running').map((t) => { const task = t as Record<string, unknown>; return (<Card key={task.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex-1"><p className="text-sm font-medium text-ink-500">{task.task_title as string}</p>{task.ai_reasoning && <p className="text-xs text-ink-500 mt-0.5 line-clamp-2">{(task.ai_reasoning as string).slice(0, 120)}</p>}</div><Badge tone="brand" dot>running</Badge></div></Card>); })}</div>)}
          {tab === 'completed' && (<div className="space-y-2">{wd.tasks.filter((t) => (t as Record<string, unknown>).status === 'completed').map((t) => { const task = t as Record<string, unknown>; return (<Card key={task.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex-1"><p className="text-sm font-medium text-ink-500">{task.task_title as string}</p><p className="text-xs text-ink-500 mt-0.5">{timeAgo(task.created_at as string)}</p></div><Badge tone="success" dot>completed</Badge></div></Card>); })}</div>)}
          {tab === 'approvals' && (wd.approvals.length > 0 ? (<div className="space-y-2">{wd.approvals.map((a) => { const ap = a as Record<string, unknown>; const task = wd.tasks.find((t) => (t as Record<string, unknown>).id === ap.task_id) as Record<string, unknown> | undefined; return (<Card key={ap.id as string} className="p-3 space-y-2"><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-ink-500">{task?.task_title as string ?? 'Task'}</p><p className="text-xs text-ink-500">{task?.task_description as string ?? ''}</p></div><Badge tone="warning">{ap.approval_level as string}</Badge></div><div className="flex items-center gap-2"><Badge tone="brand"><Sparkles className="h-3 w-3 mr-1" />{(ap.confidence_at_request as number ?? 0).toFixed(0)}%</Badge><span className="text-xs text-ink-500">{timeAgo(ap.created_at as string)}</span></div><div className="flex items-center gap-2"><button onClick={() => handleApprove(ap.task_id as string)} className="rounded-lg bg-success-500/10 px-3 py-1.5 text-xs text-success-400 hover:bg-success-500/20">Approve</button><button onClick={() => handleReject(ap.task_id as string)} className="rounded-lg bg-error-500/10 px-3 py-1.5 text-xs text-error-400 hover:bg-error-500/20">Reject</button></div></Card>); })}</div>) : <div className="text-center py-8 text-sm text-ink-500">No pending approvals.</div>)}
          {tab === 'workflows' && (wd.workflows.length > 0 ? (<div className="space-y-2">{wd.workflows.map((w) => { const wf = w as Record<string, unknown>; return (<Card key={wf.id as string} className="p-3"><div className="flex items-start justify-between"><div className="flex items-center gap-2"><Layers className="h-4 w-4 text-brand-400" /><div><p className="text-sm font-medium text-ink-500">{wf.workflow_name as string}</p><p className="text-xs text-ink-500">{wf.workflow_type as string} · {wf.execution_count as number} runs</p></div></div><Badge tone={wf.is_active ? 'success' : 'neutral'}>{wf.is_active ? 'Active' : 'Inactive'}</Badge></div></Card>); })}</div>) : <div className="text-center py-8 text-sm text-ink-500">No workflows configured.</div>)}
          {tab === 'collaboration' && (wd.collaborations.length > 0 ? (<div className="space-y-2">{wd.collaborations.map((c) => { const col = c as Record<string, unknown>; return (<Card key={col.id as string} className="p-3"><div className="flex items-center gap-2"><RefreshCw className="h-3 w-3 text-brand-400" /><Badge tone="brand">{col.collaboration_type as string}</Badge></div></Card>); })}</div>) : <div className="text-center py-8 text-sm text-ink-500">No agent collaborations.</div>)}
          {tab === 'performance' && (wd.performance.length > 0 ? (<div className="space-y-2">{wd.performance.map((p) => { const perf = p as Record<string, unknown>; return (<Card key={perf.id as string} className="p-3"><p className="text-sm text-ink-500">{perf.performance_date as string}</p><p className="text-xs text-ink-500">Completed: {perf.tasks_completed as number} · Failed: {perf.tasks_failed as number} · Success: {(perf.success_rate as number).toFixed(0)}%</p></Card>); })}</div>) : <div className="text-center py-8 text-sm text-ink-500">No performance data yet.</div>)}
          {tab === 'learning' && <GenericList items={wd.learnings as Array<Record<string, unknown>>} icon={Lightbulb} titleKey="learning_title" descKey="learning_description" />}
          {tab === 'memory' && <GenericList items={wd.memories as Array<Record<string, unknown>>} icon={Brain} titleKey="memory_title" descKey="memory_content" />}
          {tab === 'reasoning' && <GenericList items={wd.reasoning as Array<Record<string, unknown>>} icon={Brain} titleKey="reasoning_title" descKey="reasoning_text" />}
          {tab === 'results' && <GenericList items={wd.results as Array<Record<string, unknown>>} icon={CheckCircle2} titleKey="result_summary" descKey="ai_reasoning" />}
          {tab === 'errors' && <GenericList items={wd.errors as Array<Record<string, unknown>>} icon={AlertTriangle} titleKey="error_message" descKey="error_type" />}
          {tab === 'metrics' && <GenericList items={wd.metrics as Array<Record<string, unknown>>} icon={Activity} titleKey="metric_name" descKey="metric_category" />}
          {tab === 'schedules' && <GenericList items={wd.schedules as Array<Record<string, unknown>>} icon={Clock} titleKey="schedule_name" descKey="schedule_type" />}
          {tab === 'logs' && <GenericList items={wd.logs as Array<Record<string, unknown>>} icon={FileText} titleKey="log_message" descKey="log_level" />}
          {tab === 'decisions' && <GenericList items={wd.decisions as Array<Record<string, unknown>>} icon={Award} titleKey="decision_title" descKey="decision_description" />}
        </div>
      </Card>
    </div>
  );
}
