import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {execFileSync,execFile} from 'node:child_process';
import {randomUUID} from 'node:crypto';
const container=process.argv[2];assert.match(container??'',/^yuktris-acquisition-regression-/);
const args=['exec','-i',container,'psql','-U','postgres','-d','postgres','-v','ON_ERROR_STOP=1','-At'];
const sql=q=>execFileSync('docker',args,{input:q,encoding:'utf8'}).trim();
const parallel=q=>new Promise((resolve,reject)=>{const p=execFile('docker',args,{encoding:'utf8'},(e,out)=>e?reject(e):resolve(out.trim()));p.stdin.end(q)});
sql(`CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
CREATE TABLE public.workspaces(id uuid PRIMARY KEY);
CREATE TABLE public.icps(id uuid PRIMARY KEY, workspace_id uuid REFERENCES workspaces(id));
CREATE TABLE public.prospects(id uuid PRIMARY KEY, workspace_id uuid);
CREATE TABLE public.linkedin_accounts(id uuid PRIMARY KEY, workspace_id uuid, connection_state text);`);
const base=readFileSync('supabase/migrations/20260904120000_autonomous_prospect_inventory.sql','utf8');
sql(base.slice(0,base.indexOf('ALTER TABLE public.customer_campaigns')));
sql(readFileSync('supabase/migrations/20260906100000_initial_acquisition_lifecycle.sql','utf8'));
sql(base.slice(base.indexOf('CREATE OR REPLACE FUNCTION public.claim_prospect_replenishment'),base.indexOf('CREATE OR REPLACE FUNCTION public.reserve_autonomous_campaign_prospects')));
const w=randomUUID(),i=randomUUID(),maintenance=randomUUID(),paused=randomUUID(),active=randomUUID();
sql(`INSERT INTO workspaces VALUES('${w}');
INSERT INTO icps(id,workspace_id,prospecting_status,acquisition_phase) VALUES
('${i}','${w}','queued','initial_acquisition'),('${maintenance}','${w}','up_to_date','maintenance'),
('${paused}','${w}','paused','initial_acquisition'),('${active}','${w}','queued','initial_acquisition');
INSERT INTO prospect_replenishment_jobs(workspace_id,icp_id,idempotency_key,reason,status)
VALUES('${w}','${active}','existing-active','icp_activated','processing');`);
const migration=readFileSync('supabase/migrations/20260909120000_senderless_prospect_acquisition.sql','utf8');
sql(migration);
assert.equal(sql(`SELECT next_refresh_at IS NOT NULL FROM icps WHERE id='${i}';`),'t');
const recovered=sql(`SELECT next_refresh_at FROM icps WHERE id='${i}';`);sql(migration);
assert.equal(sql(`SELECT next_refresh_at FROM icps WHERE id='${i}';`),recovered);
assert.equal(sql(`SELECT count(*) FROM icps WHERE id IN ('${maintenance}','${paused}','${active}') AND next_refresh_at IS NULL;`),'3');
assert.equal(sql('SELECT workspace_id FROM due_prospect_replenishment_workspaces();'),w);
assert.equal(sql(`SELECT id FROM due_prospect_replenishment_icp('${w}');`),i);
const enqueue=(id=i,reason='scheduled_refresh')=>`SELECT enqueue_prospect_replenishment('${w}','${id}','${reason}');`;
const results=await Promise.all(Array.from({length:12},(_,n)=>parallel(enqueue(i,n%2?'icp_activated':'scheduled_refresh'))));
const jobs=results.map(r=>JSON.parse(r).job_id);assert.equal(new Set(jobs).size,1);
assert.equal(sql(`SELECT count(*) FROM prospect_replenishment_jobs WHERE icp_id='${i}';`),'1');
assert.equal(sql(`SELECT linkedin_account_id IS NULL FROM prospect_replenishment_jobs WHERE icp_id='${i}';`),'t');
assert.equal(sql(`SELECT initial_acquisition_batches_completed FROM icps WHERE id='${i}';`),'0');
const claims=await Promise.all(Array.from({length:8},(_,n)=>parallel(`SELECT claim_prospect_replenishment('${jobs[0]}','${w}','local-test-${n}');`)));
assert.equal(claims.map(JSON.parse).filter(x=>x.claimed).length,1);
assert.equal(sql(`SELECT attempt_count FROM prospect_replenishment_jobs WHERE icp_id='${i}';`),'1');
sql(`UPDATE prospect_replenishment_jobs SET status='completed' WHERE id='${jobs[0]}';`);
assert.equal(JSON.parse(sql(enqueue())).job_id,jobs[0]);
assert.equal(sql(`SELECT count(*) FROM prospect_replenishment_jobs WHERE icp_id='${i}';`),'1');
sql(`UPDATE icps SET next_refresh_at=now()+interval '10 minutes',initial_acquisition_batches_completed=1 WHERE id='${i}';`);
assert.equal(JSON.parse(sql(enqueue())).job_id,null);
sql(`UPDATE icps SET next_refresh_at=now()-interval '1 second' WHERE id='${i}';`);
assert.notEqual(JSON.parse(sql(enqueue())).job_id,jobs[0]);
assert.equal(sql(`SELECT initial_acquisition_batches_completed FROM icps WHERE id='${i}';`),'1');
sql(`UPDATE prospect_replenishment_jobs SET status='cooldown',next_attempt_at=now()+interval '15 minutes' WHERE icp_id='${i}' AND status='queued';
UPDATE icps SET next_refresh_at=now()-interval '1 second' WHERE id='${maintenance}';`);
assert.equal(sql(`SELECT id FROM due_prospect_replenishment_icp('${w}');`),maintenance);
sql(enqueue(maintenance));assert.equal(sql(`SELECT acquisition_phase FROM icps WHERE id='${maintenance}';`),'maintenance');
const connected=randomUUID();sql(`INSERT INTO linkedin_accounts VALUES('${randomUUID()}','${w}','connected');
INSERT INTO icps(id,workspace_id,prospecting_status,acquisition_phase,next_refresh_at) VALUES('${connected}','${w}','queued','initial_acquisition',now());`);
const connectedJob=JSON.parse(sql(enqueue(connected,'icp_activated'))).job_id;assert.ok(connectedJob);
assert.equal(JSON.parse(sql(enqueue(connected,'icp_activated'))).job_id,connectedJob);
sql(`UPDATE prospect_replenishment_jobs SET status='completed' WHERE icp_id='${maintenance}';
UPDATE icps SET initial_acquisition_batches_completed=3,next_refresh_at=now()+interval '6 hours' WHERE id='${maintenance}';`);
sql(enqueue(maintenance,'targeting_changed'));
assert.equal(sql(`SELECT acquisition_phase||':'||initial_acquisition_batches_completed FROM icps WHERE id='${maintenance}';`),'initial_acquisition:0');
assert.equal(sql(`SELECT initial_acquisition_batches_completed FROM icps WHERE id='${i}';`),'1');
assert.equal(sql(`SELECT has_function_privilege('authenticated','enqueue_prospect_replenishment(uuid,uuid,text)','EXECUTE');`),'f');
assert.equal(sql(`SELECT has_function_privilege('service_role','enqueue_prospect_replenishment(uuid,uuid,text)','EXECUTE');`),'t');
for(let n=0;n<15;n++){const ws=randomUUID();sql(`INSERT INTO workspaces VALUES('${ws}');INSERT INTO icps(id,workspace_id,prospecting_status,next_refresh_at) VALUES('${randomUUID()}','${ws}','queued',now());`)}
assert.equal(sql('SELECT count(*) FROM due_prospect_replenishment_workspaces();'),'10');
assert.equal(sql("SELECT count(*) FROM (SELECT icp_id FROM prospect_replenishment_jobs WHERE status IN ('queued','processing','cooldown') GROUP BY icp_id HAVING count(*)>1) d;"),'0');
console.log('PASS PostgreSQL: narrow recovery, senderless/connected jobs, 12 concurrent enqueues -> 1 job, 8 concurrent claims -> 1 claim, completion gap, cooldown, maintenance, retargeting, permissions, bounded tick');