/*
# Create Prospect Discovery Agent Schema

## Overview
Creates the complete database schema for the Prospect Discovery Agent.
This agent discovers companies matching ICPs generated by the ICP Intelligence Agent.
It runs after the Business Intelligence, Market Intelligence, and ICP Intelligence agents complete.

## New Tables (4 total)

1. **prospect_discovery** — Main discovery run record. Links to an ICP and tracks the overall
   discovery status, total companies found, qualified count, and high-priority count.

2. **discovered_companies** — Individual discovered companies. Named differently from the
   existing `companies` table (from the CRM module) to avoid conflicts. Each company has website,
   industry, country, employee count, annual revenue, company size, growth stage, technology stack,
   description, opportunity score, growth score, ICP match score, priority, and status.

3. **company_scores** — Detailed scoring breakdown for each discovered company: revenue score,
   growth score, competition score, technology score, market score, and overall score.

4. **prospect_recommendations** — AI-generated recommendations for each company: recommendation
   text, priority, and reason. Named differently to avoid conflicts with existing tables.

## Security
- RLS enabled on ALL tables.
- All tables scoped to workspace membership via is_workspace_member() function.
- Child tables scope through prospect_discovery or discovered_companies using EXISTS subquery.
- 4 CRUD policies per table (select, insert, update, delete) — no FOR ALL.
- All policies use TO authenticated.

## Important Notes
1. The prospect_discovery table links to icps via icp_id (nullable — allows discovery without ICP).
2. discovered_companies cascade delete when a discovery run is deleted.
3. company_scores and prospect_recommendations cascade delete when a company is deleted.
4. Indexes created on workspace_id (prospect_discovery), discovery_id (discovered_companies), and
   company_id (company_scores, prospect_recommendations) for query performance.
5. The updated_at trigger on prospect_discovery auto-updates the timestamp on row modification.
*/

-- ============================================================
-- 1. prospect_discovery (main table)
-- ============================================================

CREATE TABLE IF NOT EXISTS prospect_discovery (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  icp_id uuid REFERENCES icps(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'processing', 'completed', 'failed')),
  total_found integer NOT NULL DEFAULT 0,
  qualified_count integer NOT NULL DEFAULT 0,
  high_priority_count integer NOT NULL DEFAULT 0,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prospect_discovery_workspace_id ON prospect_discovery(workspace_id);
CREATE INDEX IF NOT EXISTS idx_prospect_discovery_icp_id ON prospect_discovery(icp_id);
CREATE INDEX IF NOT EXISTS idx_prospect_discovery_status ON prospect_discovery(status);

ALTER TABLE prospect_discovery ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_discoveries" ON prospect_discovery;
CREATE POLICY "select_own_discoveries" ON prospect_discovery FOR SELECT
  TO authenticated USING (is_workspace_member(workspace_id));

DROP POLICY IF EXISTS "insert_own_discoveries" ON prospect_discovery;
CREATE POLICY "insert_own_discoveries" ON prospect_discovery FOR INSERT
  TO authenticated WITH CHECK (is_workspace_member(workspace_id));

DROP POLICY IF EXISTS "update_own_discoveries" ON prospect_discovery;
CREATE POLICY "update_own_discoveries" ON prospect_discovery FOR UPDATE
  TO authenticated USING (is_workspace_member(workspace_id)) WITH CHECK (is_workspace_member(workspace_id));

DROP POLICY IF EXISTS "delete_own_discoveries" ON prospect_discovery;
CREATE POLICY "delete_own_discoveries" ON prospect_discovery FOR DELETE
  TO authenticated USING (is_workspace_member(workspace_id));

-- ============================================================
-- 2. discovered_companies
-- ============================================================

CREATE TABLE IF NOT EXISTS discovered_companies (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  discovery_id uuid NOT NULL REFERENCES prospect_discovery(id) ON DELETE CASCADE,
  company_name text NOT NULL,
  website text,
  industry text,
  country text,
  employee_count text,
  annual_revenue text,
  company_size text,
  growth_stage text,
  technology_stack text[] DEFAULT '{}',
  description text,
  opportunity_score integer DEFAULT 0,
  growth_score integer DEFAULT 0,
  icp_match_score integer DEFAULT 0,
  priority text DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  status text DEFAULT 'discovered' CHECK (status IN ('discovered', 'qualified', 'saved', 'ignored', 'researching')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_discovered_companies_discovery_id ON discovered_companies(discovery_id);
CREATE INDEX IF NOT EXISTS idx_discovered_companies_status ON discovered_companies(status);
CREATE INDEX IF NOT EXISTS idx_discovered_companies_priority ON discovered_companies(priority);
CREATE INDEX IF NOT EXISTS idx_discovered_companies_opportunity_score ON discovered_companies(opportunity_score DESC);

ALTER TABLE discovered_companies ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_discovered_companies" ON discovered_companies;
CREATE POLICY "select_own_discovered_companies" ON discovered_companies FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM prospect_discovery WHERE prospect_discovery.id = discovered_companies.discovery_id AND is_workspace_member(prospect_discovery.workspace_id))
  );

DROP POLICY IF EXISTS "insert_own_discovered_companies" ON discovered_companies;
CREATE POLICY "insert_own_discovered_companies" ON discovered_companies FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM prospect_discovery WHERE prospect_discovery.id = discovered_companies.discovery_id AND is_workspace_member(prospect_discovery.workspace_id))
  );

DROP POLICY IF EXISTS "update_own_discovered_companies" ON discovered_companies;
CREATE POLICY "update_own_discovered_companies" ON discovered_companies FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM prospect_discovery WHERE prospect_discovery.id = discovered_companies.discovery_id AND is_workspace_member(prospect_discovery.workspace_id))
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM prospect_discovery WHERE prospect_discovery.id = discovered_companies.discovery_id AND is_workspace_member(prospect_discovery.workspace_id))
  );

DROP POLICY IF EXISTS "delete_own_discovered_companies" ON discovered_companies;
CREATE POLICY "delete_own_discovered_companies" ON discovered_companies FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM prospect_discovery WHERE prospect_discovery.id = discovered_companies.discovery_id AND is_workspace_member(prospect_discovery.workspace_id))
  );

-- ============================================================
-- 3. company_scores
-- ============================================================

CREATE TABLE IF NOT EXISTS company_scores (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES discovered_companies(id) ON DELETE CASCADE,
  revenue_score integer DEFAULT 0,
  growth_score integer DEFAULT 0,
  competition_score integer DEFAULT 0,
  technology_score integer DEFAULT 0,
  market_score integer DEFAULT 0,
  overall_score integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_company_scores_company_id ON company_scores(company_id);

ALTER TABLE company_scores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_company_scores" ON company_scores;
CREATE POLICY "select_own_company_scores" ON company_scores FOR SELECT
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = company_scores.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

DROP POLICY IF EXISTS "insert_own_company_scores" ON company_scores;
CREATE POLICY "insert_own_company_scores" ON company_scores FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = company_scores.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

DROP POLICY IF EXISTS "update_own_company_scores" ON company_scores;
CREATE POLICY "update_own_company_scores" ON company_scores FOR UPDATE
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = company_scores.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = company_scores.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

DROP POLICY IF EXISTS "delete_own_company_scores" ON company_scores;
CREATE POLICY "delete_own_company_scores" ON company_scores FOR DELETE
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = company_scores.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

-- ============================================================
-- 4. prospect_recommendations
-- ============================================================

CREATE TABLE IF NOT EXISTS prospect_recommendations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES discovered_companies(id) ON DELETE CASCADE,
  recommendation text NOT NULL,
  priority text DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_prospect_recommendations_company_id ON prospect_recommendations(company_id);

ALTER TABLE prospect_recommendations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_prospect_recommendations" ON prospect_recommendations;
CREATE POLICY "select_own_prospect_recommendations" ON prospect_recommendations FOR SELECT
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = prospect_recommendations.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

DROP POLICY IF EXISTS "insert_own_prospect_recommendations" ON prospect_recommendations;
CREATE POLICY "insert_own_prospect_recommendations" ON prospect_recommendations FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = prospect_recommendations.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

DROP POLICY IF EXISTS "update_own_prospect_recommendations" ON prospect_recommendations;
CREATE POLICY "update_own_prospect_recommendations" ON prospect_recommendations FOR UPDATE
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = prospect_recommendations.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = prospect_recommendations.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

DROP POLICY IF EXISTS "delete_own_prospect_recommendations" ON prospect_recommendations;
CREATE POLICY "delete_own_prospect_recommendations" ON prospect_recommendations FOR DELETE
  TO authenticated USING (
    EXISTS (
      SELECT 1 FROM discovered_companies
      JOIN prospect_discovery ON prospect_discovery.id = discovered_companies.discovery_id
      WHERE discovered_companies.id = prospect_recommendations.company_id AND is_workspace_member(prospect_discovery.workspace_id)
    )
  );

-- ============================================================
-- Trigger: auto-update updated_at on prospect_discovery
-- ============================================================

CREATE OR REPLACE FUNCTION update_prospect_discovery_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_prospect_discovery_updated_at ON prospect_discovery;
CREATE TRIGGER trigger_prospect_discovery_updated_at
  BEFORE UPDATE ON prospect_discovery
  FOR EACH ROW
  EXECUTE FUNCTION update_prospect_discovery_updated_at();
